# Generated by Django 4.1.7 on 2023-03-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('credit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directed_amount', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payment.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('state', models.CharField(choices=[('SUC', 'Successful'), ('FAI', 'Failed')], default='FAI', max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountRechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('state', models.CharField(choices=[('SUC', 'Successful'), ('FAI', 'Failed')], default='FAI', max_length=10)),
                ('operation', models.CharField(choices=[('INC', 'Increase Credit'), ('DEC', 'Decrease Credit')], default='INC', max_length=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.seller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
