# Generated by Django 4.1.7 on 2023-03-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountrechargeorder',
            old_name='operation',
            new_name='action',
        ),
    ]
